# Generated by Django 4.2 on 2023-05-14 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [

    ]
